### ISSUE TITLE
Cannot read properties of undefined (reading 'load').

### ISSUE THREAD

**Issue by ultragrup** [elegantapp/pwa-asset-generator#1014]
An error occurs when attempting to generate images using an AM cli tool. The index.html does not update as expected, and the following TypeError is thrown: TypeError: Cannot read properties of undefined (reading 'load').

To Reproduce Steps to reproduce the behavior:

Execute cli command  :   pwa-asset-generator OIP.jpg -i ./index.html -m ./manifest.json

Open 'index.html' [This file is expected to be updated]
See error: TypeError: Cannot read properties of undefined (reading 'load')
Expected behavior The expected behavior was for the index.html to be updated with the generated images without any errors.

OS: Windows 11
node version: v18.20.3 [Obtained using node --version]
npm version: 10.7.0 [Obtained using npm --version]
cli version: 2.17.27

![Screenshot 2024-08-19 140808](https://github.com/user-attachments/assets/d2a72954-4948-4139-b303-c29ee8c914ea)

**Comment by jashson** [comment]
Same problem happens after I did some package updates in my package.json. The interesting thing is, that when running `pwa-asset-generator` via an npm script (`npm run` ...) it will throw that error and the index.html is not being updated. But when i call the exact same command directly in the terminal there are no errors (beside the error, that the apple design guidelines could not be loaded, which works with `npm run` ...😳)

pwa-asset-generator: 6.3.1
OS: macOS 14.6.1
node: v20.17.0
npm: 10.8.2

**Comment by PhilippPriller** [comment]
The root of the issue is the package cheerio.
`"cheerio": "^1.0.0-rc.12"`
They recently released version 1.0.0 which contains breaking changes and has some major issues (from what I've gathered).
Since the version was specified with the ^ the new version is automatically used and therefore breaks the asset-generator as well

**Comment by onderceylan** [comment]
@atjn thank you for the fix! And, thanks for reporting this issue folks. Can anybody verify the fix with version 6.3.2 please?
