### ISSUE TITLE
Allow background images

### ISSUE THREAD

**Issue by djmtype** [elegantapp/pwa-asset-generator#962]
**Is your feature request related to a problem? Please describe.**
There is no way to choose an image to use for a background; only css.

**Describe the solution you'd like**
A way to specify the path to a background image. 

**Additional context**
An example of a prompt for splash screens: 
```
pwa-asset-generator public/logo.svg ./assets -b public/bk.jpg --splash-only
```

**Comment by onderceylan** [comment]
Hi @djmtype, that's already possible in the current version. You can either use CSS background URLs or your custom HTML inputs to accomplish that.

Examples;
```
# Option 1
pwa-asset-generator icon.svg ./assets -b "url(https://wallpapercrafter.com/sizes/2560x1440/10631-starry-sky-stars-space-dark-astronomy-4k.jpg) no-repeat center center fixed"

# Option 2
pwa-asset-generator icon-with-custom-bg.html ./assets
```

**Comment by djmtype** [comment]
@onderceylan I must be doing something wrong because that produced results with a white background. I tried using npx and npm to run the command. https://github.com/djmtype/pwa-gen-test/blob/main/package.json#L10

**Comment by djmtype** [comment]
Thanks @onderceylan!

**Comment by djmtype** [comment]
@onderceylan The one significant thing I wanted to mention is that in order to use Option 1, is that I couldn't reference an image relative to my project. It's required the url address needs to be from full url. So using `url(/public/bk.jpg)` or `url(./public/bk.jpg)` or `url(public/bk.jpg)`didn't work in any case.

**Comment by onderceylan** [comment]
That's right. It has to be a remote URL, or a local web server URL in your machine. If you really need to use relative path, best option would be doing that with your own html input. It provides so much flexibility including using relative image paths.

**Comment by djmtype** [comment]
> best option would be doing that with your own html input.

Exactly, thank you.
