### ISSUE TITLE
When running with -p "0px" option I get icon size 192x196, 512x516 instead of 192x192, 512x512

### ISSUE THREAD

**Issue by TheRealMaN** [elegantapp/pwa-asset-generator#999]
**Describe the bug**
When running with -p "0px" option I get icon size 192x196px, 512x516px instead of 192x192px, 512x512px

**To Reproduce**
pwa-asset-generator icon.svg ./_nuxt/assets -i ./index.html -m ./manifest.json -b "#51B016" -p "0px"
OR
pwa-asset-generator icon.svg ./_nuxt/assets -i ./index.html -m ./manifest.json -b "#51B016" -p "0"

**Expected behavior**
To get the exact 192x192px, 512x512px icon sizes

**System (please complete the following information):**
 - OS: macOS Monterey
 - node version v18.16.0
 - npm 9.5.1

**Screenshots**

![manifest-icon-192 maskable](https://github.com/elegantapp/pwa-asset-generator/assets/5158427/b56e4e91-ebc2-40e4-9313-8520ec4d5238)
![manifest-icon-512 maskable](https://github.com/elegantapp/pwa-asset-generator/assets/5158427/b24b8fc5-5369-43df-b1da-9b059ac94ffa)

**Comment by onderceylan** [comment]
Hi @TheRealMaN, thanks for the issue. I was able to reproduce it, and I will publish a fix soon.
